### ISSUE TITLE
Ubuntu 12 getting error while kitchen converge

### ISSUE THREAD

**Issue by joelhandwell** [haapp/w_apache#29]
Experiencing following error while running on ubuntu 12:

```

           ================================================================================
           Error executing action `install` on resource 'apt_package[libapache2-mod-fastcgi]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '100'
           ---- Begin output of apt-get -q -y install libapache2-mod-fastcgi=2.4.7~0910052141-1 ----

           Building dependency tree...
           Reading state information...
           The following packages were automatically installed and are no longer required:
             apache2-bin liblua5.1-0 apache2-data
           Use 'apt-get autoremove' to remove them.
           The following extra packages will be installed:
             apache2.2-bin apache2.2-common
           Suggested packages:
             www-browser apache2-doc apache2-suexec apache2-suexec-custom
           The following packages will be REMOVED:
             apache2
           The following NEW packages will be installed:
             apache2.2-bin apache2.2-common libapache2-mod-fastcgi
           0 upgraded, 3 newly installed, 1 to remove and 43 not upgraded.
           Need to get 1625 kB of archives.
           After this operation, 4332 kB of additional disk space will be used.
           Get:1 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main apache2.2-bin amd64 2.2.22-1ubuntu1.10 [1343kB]
           Get:2 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main apache2.2-common amd64 2.2.22-1ubuntu1.10 [226 kB]
           Get:3 http://us.archive.ubuntu.com/ubuntu/ precise/multiverse libapache2-mod-fastcgi amd64 2.4.7~0910052141-1 [55.2 kB]
       Fetched 1625 kB in 24s (65.5 kB/s)
           (Reading database ... 40057 files and directories currently installed.)
           Removing apache2 ...
            * Stopping web server apache2
            *
           Processing triggers for ureadahead ...
       Processing triggers for man-db ...
           Selecting previously unselected package apache2.2-bin.
           (Reading database ... 40010 files and directories currently installed.)
           Unpacking apache2.2-bin (from .../apache2.2-bin_2.2.22-1ubuntu1.10_amd64.deb) ...
           Selecting previously unselected package apache2.2-common.
           Unpacking apache2.2-common (from .../apache2.2-common_2.2.22-1ubuntu1.10_amd64.deb) ...
           Selecting previously unselected package libapache2-mod-fastcgi.
           Unpacking libapache2-mod-fastcgi (from .../libapache2-mod-fastcgi_2.4.7~0910052141-1_amd64.deb) ...
           Processing triggers for man-db ...
           STDERR: dpkg: error processing /var/cache/apt/archives/apache2.2-bin_2.2.22-1ubuntu1.10_amd64.deb (--unpack):


           dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
           dpkg: error processing /var/cache/apt/archives/apache2.2-common_2.2.22-1ubuntu1.10_amd64.deb (--unpack):
            trying to overwrite '/usr/share/man/man8/apache2.8.gz', which is also in package apache2-bin 2.4.16-4+deb.sury.org~precise+4
           dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
           Errors were encountered while processing:
            /var/cache/apt/archives/apache2.2-bin_2.2.22-1ubuntu1.10_amd64.deb
            /var/cache/apt/archives/apache2.2-common_2.2.22-1ubuntu1.10_amd64.deb
           E: Sub-process /usr/bin/dpkg returned an error code (1)
           ---- End output of apt-get -q -y install libapache2-mod-fastcgi=2.4.7~0910052141-1 ----
           Ran apt-get -q -y install libapache2-mod-fastcgi=2.4.7~0910052141-1 returned 100

           Resource Declaration:
           ---------------------
       # In /tmp/kitchen/cache/cookbooks/apache2/recipes/mod_fastcgi.rb

            25:     package 'libapache2-mod-fastcgi'
            26:   end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/apache2/recipes/mod_fastcgi.rb:25:in `from_file'

           apt_package("libapache2-mod-fastcgi") do

             retries 0
             retry_delay 2
             default_guard_interpreter :default
             package_name "libapache2-mod-fastcgi"

             cookbook_name "apache2"
             recipe_name "mod_fastcgi"
           end

       Recipe: ntp::default
         * service[ntp] action restart
           - restart service service[ntp]
       Recipe: ntp::apparmor
         * service[apparmor] action restart
           - restart service service[apparmor]
       Recipe: timezone-ii::debian

           - execute "bash"  "/tmp/chef-script20160104-1488-1pxv3jo"
       Recipe: w_apache::default

           * file[/etc/default/ufw-chef.rules] action create
             - update content in file /etc/default/ufw-chef.rules from fa85ee to 1576d3
             --- /etc/default/ufw-chef.rules    2016-01-03 23:11:54.857050004 -0500
             +++ /etc/default/.ufw-chef.rules20160103-1488-1592u7j      2016-01-03 23:15:54.546181998 -0500
             @@ -1,2 +1,4 @@
             -# created by chef to allow service to start
             +# position 50
             +ufw allow in proto tcp to any port 22 from 0.0.0.0/0
             +ufw allow in proto tcp to any port 2812 from any

       Recipe: apache2::default
        (up to date)
         * service[apache2] action restart

           ================================================================================
           Error executing action `restart` on resource 'service[apache2]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /etc/init.d/apache2 restart ----
           STDOUT: * Restarting web server apache2
       ...fail!

           STDERR: Output of config test was:
           env: apache2ctl: No such file or directory
           ---- End output of /etc/init.d/apache2 restart ----
           Ran /etc/init.d/apache2 restart returned 1

           Resource Declaration:
       ---------------------
           # In /tmp/kitchen/cache/cookbooks/apache2/recipes/default.rb

           206: service 'apache2' do
           207:   service_name node['apache']['service_name']
           208:   case node['platform_family']
           209:   when 'rhel'
           210:     restart_command '/sbin/service httpd restart && sleep 1' if node['apache']['version'] == '2.2'
       211:     reload_command '/sbin/service httpd graceful'
           212:   when 'debian'
           213:     provider Chef::Provider::Service::Debian
           214:   when 'arch'
           215:     service_name 'httpd'
           216:   end
           217:   supports [:start, :restart, :reload, :status]

           Compiled Resource:
           ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/apache2/recipes/default.rb:206:in `from_file'

           service("apache2") do
             provider Chef::Provider::Service::Debian
         action [:enable, :start]
             supports {:restart=>true, :reload=>true, :status=>true, :start=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "apache2"
             enabled true
             pattern "apache2"

             cookbook_name "apache2"
             recipe_name "default"
             only_if "/usr/sbin/apache2 -t"
           end

```

**Comment by osenhaji** [comment]
have you fixed the problem ?

**Comment by joelhandwell** [comment]
@osenhaji not yet. For now I recommend to use Ubuntu 14. The problem is [ppa](https://launchpad.net/~ondrej/+archive/ubuntu/apache2) for libapache-mod-fastcgi dropped support for Ubuntu 12, and I did not find alternative way to install fastcgi for apache 2.4. Maybe source compile would work. If you can create pull request for this, it's very welcomed.

**Comment by joelhandwell** [comment]
Ubuntu 12 reaching its end of life, and Ubuntu 16 getting more popular in production, I'm closing this issue. Please comment or re-open if needed.
